/*
-- FINAL 계정 생성
CREATE USER FINAL IDENTIFIED BY 1234;
GRANT CONNECT , RESOURCE TO FINAL;
-- ORA-01950 발생 시
ALTER USER FINAL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/




-- DROP
DROP TABLE MEMBER CASCADE CONSTRAINTS; 
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE GALLERY CASCADE CONSTRAINTS;
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_NOTICE_NO;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_GALLERY_NO;
DROP SEQUENCE SEQ_ATTACHMENT_NO;
DROP SEQUENCE SEQ_REPLY_NO;


-- MEMBER
CREATE TABLE MEMBER(
    NO              NUMBER        PRIMARY KEY
    , ID            VARCHAR2(100) NOT NULL UNIQUE
    , PWD           VARCHAR2(100) NOT NULL
    , NICK          VARCHAR2(100) UNIQUE
    , PROFILE       VARCHAR2(100)
    , HOBBY         VARCHAR2(100)
    , STATUS        CHAR(1)       DEFAULT 'O' CHECK (STATUS IN ('O', 'X'))
    , ENROLL_DATE   TIMESTAMP     DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP
);
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;


-- NOTICE
CREATE TABLE NOTICE(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP       
    , STATUS        CHAR(1)         DEFAULT 'O' CHECK (STATUS IN ('O','X'))
    , HIT           NUMBER          DEFAULT 0
);
CREATE SEQUENCE SEQ_NOTICE_NO NOCYCLE NOCACHE;

-- BOARD
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER
    , CATEGORY_NO   NUMBER
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'O' CHECK( STATUS IN ('O' , 'X') )
    , MODIFY_DATE   TIMESTAMP     
    , HIT           NUMBER          DEFAULT 0
);
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;


-- ATTACHMENT
CREATE TABLE ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , BNO           NUMBER
    , ORIGIN_NAME   VARCHAR2(1000)  NOT NULL
    , CHANGE_NAME   VARCHAR2(1000)  NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'O' CHECK ( STATUS IN ('O' , 'X') )
);
CREATE SEQUENCE SEQ_ATTACHMENT_NO NOCACHE NOCYCLE;

--REPLY
CREATE TABLE REPLY(
    NO              NUMBER          PRIMARY KEY
    , BNO           NUMBER          NOT NULL
    , CONTENT       VARCHAR2(1000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'O' CHECK ( STATUS IN ('O' , 'X') )
);
CREATE SEQUENCE SEQ_REPLY_NO NOCACHE NOCYCLE;


--GALLERY
CREATE TABLE GALLERY(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , ORIGIN_NAME   VARCHAR2(1000)  NOT NULL
    , CHANGE_NAME   VARCHAR2(1000)  NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'O' CHECK( STATUS IN ('O','X') )
    , HIT           NUMBER          DEFAULT 0
);
CREATE SEQUENCE SEQ_GALLERY_NO NOCACHE NOCYCLE;

--CATEGORY
CREATE TABLE CATEGORY(
    NO          NUMBER          NOT NULL UNIQUE
    , NAME      VARCHAR2(100)   NOT NULL UNIQUE
);


-- 외래키
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_ATTACHMENT_BOARD FOREIGN KEY (BNO) REFERENCES BOARD(NO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_BOARD FOREIGN KEY (BNO) REFERENCES BOARD(NO);
ALTER TABLE GALLERY ADD CONSTRAINT FK_GALLERY_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(NO);

-- 샘플 데이터 (CATEGORY)
INSERT INTO CATEGORY (NO, NAME) VALUES(10 , '자유');
INSERT INTO CATEGORY (NO, NAME) VALUES(20 , '코딩');
INSERT INTO CATEGORY (NO, NAME) VALUES(30 , '게임');
INSERT INTO CATEGORY (NO, NAME) VALUES(40 , '운동');
INSERT INTO CATEGORY (NO, NAME) VALUES(50 , '요리');
COMMIT;

--샘플 데이터 (MEMBER)
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL , 'ADMIN', '1234', '관리자');
COMMIT;

--샘플 데이터 (NOTICE)
INSERT INTO NOTICE (NO, TITLE, CONTENT) VALUES (SEQ_NOTICE_NO.NEXTVAL, '샘플 공지사항ㅋㅋ', '공지사항내용 ㅎㅎ');
INSERT INTO NOTICE (NO, TITLE, CONTENT) VALUES (SEQ_NOTICE_NO.NEXTVAL, '샘플 공지사항222ㅋㅋ', '공지사항내용22ㅎㅎ');
INSERT INTO NOTICE (NO, TITLE, CONTENT) VALUES (SEQ_NOTICE_NO.NEXTVAL, '샘플 공지사항333ㅋㅋ', '공지사항내용33ㅎㅎ');
COMMIT;

--샘플 데이터 (BOARD)
INSERT INTO BOARD ( NO ,TITLE ,CONTENT ,WRITER_NO ,CATEGORY_NO ) VALUES ( SEQ_BOARD_NO.NEXTVAL ,'제목ㅋㅋㅋ11111' ,'내용ㅋㅋㅋ내용내용' ,1 ,10 );
INSERT INTO BOARD ( NO ,TITLE ,CONTENT ,WRITER_NO ,CATEGORY_NO ) VALUES ( SEQ_BOARD_NO.NEXTVAL ,'제목ㅋㅋㅋ안녕' ,'내용ㅋㅋㅋ용내용내' ,1 ,20 );
INSERT INTO BOARD ( NO ,TITLE ,CONTENT ,WRITER_NO ,CATEGORY_NO ) VALUES ( SEQ_BOARD_NO.NEXTVAL ,'제목ㅋㅋㅋ반가워' ,'내용ㅋㅋㅋ안경' ,1 ,30 );
INSERT INTO BOARD ( NO ,TITLE ,CONTENT ,WRITER_NO ,CATEGORY_NO ) VALUES ( SEQ_BOARD_NO.NEXTVAL ,'제목ㅋㅋㅋ오늘은' ,'내용ㅋㅋㅋ핸드폰' ,1 ,40 );
INSERT INTO BOARD ( NO ,TITLE ,CONTENT ,WRITER_NO ,CATEGORY_NO ) VALUES ( SEQ_BOARD_NO.NEXTVAL ,'제목ㅋㅋㅋ화요일' ,'내용ㅋㅋㅋ칫솔' ,1 ,50 );
INSERT INTO BOARD ( NO ,TITLE ,CONTENT ,WRITER_NO ,CATEGORY_NO ) VALUES ( SEQ_BOARD_NO.NEXTVAL ,'제목ㅋㅋㅋ이따가병원가야지ㅎㅎ' ,'내용ㅋㅋㅋ종이컵' ,1 ,NULL );
COMMIT;








