/*
-- FINAL 계정 생성
CREATE USER FINAL IDENTIFIED BY 1234;
GRANT CONNECT , RESOURCE TO FINAL;
-- ORA-01950 발생 시
ALTER USER FINAL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/


-- MEMBER
CREATE TABLE MEMBER(
    ID          VARCHAR2(100)
    , PWD       VARCHAR2(100)
    , NICK      VARCHAR2(100)
);


