-- 계정 생성에 사용했던 스크립트 (SYSTEM 계정으로 접속해서 실행함)
/*
CREATE USER SEMI IDENTIFIED BY 1234;
GRANT RESOURCE , CONNECT TO SEMI;
ALTER USER SEMI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/



-- MEMBER
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY 
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , HOBBY         VARCHAR2(100)   
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , QUIT_YN       CHAR(1)         DEFAULT 'N' CHECK( QUIT_YN IN('Y','N') )
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- BOARD
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(400)   NOT NULL
    , WRITER        NUMBER          NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DELETE_YN     CHAR(1)         DEFAULT 'N' CHECK( DELETE_YN IN('Y','N') )
    , CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO)
);

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;





-- 테스트

-- 게시글 조회
SELECT 
    B.NO
    , B.TITLE
    , B.CONTENT
    , B.WRITER
    , B.ENROLL_DATE
    , M.NICK
FROM BOARD B
JOIN MEMBER M ON B.WRITER = M.NO
WHERE B.DELETE_YN = 'N'
;

INSERT INTO BOARD(NO , TITLE , CONTENT , WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL , '제목01' , '내용01' , 7);
INSERT INTO BOARD(NO , TITLE , CONTENT , WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL , '제목02' , '내용02' , 7);
INSERT INTO BOARD(NO , TITLE , CONTENT , WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL , '제목03' , '내용03' , 7);
INSERT INTO BOARD(NO , TITLE , CONTENT , WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL , '제목04' , '내용04' , 7);
INSERT INTO BOARD(NO , TITLE , CONTENT , WRITER) VALUES (SEQ_BOARD_NO.NEXTVAL , '제목05' , '내용05' , 7);

commit;














