-- 계정 생성에 사용했던 스크립트 (SYSTEM 계정으로 접속해서 실행함)
/*
CREATE USER SEMI IDENTIFIED BY 1234;
GRANT RESOURCE , CONNECT TO SEMI;
ALTER USER SEMI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
*/



-- MEMBER
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY 
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , HOBBY         VARCHAR2(100)   
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , QUIT_YN       CHAR(1)         DEFAULT 'N' CHECK( QUIT_YN IN('Y','N') )
);

DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- BOARD
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO              NUMBER          PRIMARY KEY
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(400)   NOT NULL
    , WRITER        NUMBER          NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DELETE_YN     CHAR(1)         DEFAULT 'N' CHECK( DELETE_YN IN('Y','N') )
    , HIT           NUMBER          DEFAULT 0
    , CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER) REFERENCES MEMBER(NO)
);

DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

-- ATTACHMENT
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE ATTACHMENT(
    NO              NUMBER          PRIMARY KEY
    , ORIGIN_NAME   VARCHAR2(100)   
    , CHANGE_NAME   VARCHAR2(100)   NOT NULL
    , REF_BOARD_NO  NUMBER          
    , CONSTRAINT FK_ATTACHMENT_BOARD FOREIGN KEY(REF_BOARD_NO) REFERENCES BOARD(NO)
);

DROP SEQUENCE SEQ_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_ATTACHMENT_NO NOCACHE NOCYCLE;



-- 테스트

-- 조회수 증가
select * from board;




SELECT 
    B.NO
    , B.TITLE
    , B.CONTENT
    , B.WRITER
    , B.ENROLL_DATE
    , B.HIT
    , A.CHANGE_NAME
FROM BOARD B
JOIN ATTACHMENT A ON (B.NO = A.REF_BOARD_NO)
WHERE B.NO = ? 
AND B.DELETE_YN = 'N'















