SELECT SYSDATE FROM DUAL;


-- 테이블 삭제
DROP TABLE MEMBER;

-- 테이블 생성
CREATE TABLE MEMBER(
    ID VARCHAR(100)
    , PWD VARCHAR2(100)
    , NICK VARCHAR2(100)
    , LOCATION VARCHAR2(100)
    , AGE NUMBER
);

-- 이메일 칼럼 추가
ALTER TABLE MEMBER ADD(EMAIL VARCHAR2(100));

-- 조회
SELECT * FROM MEMBER;

-- 닉네임조회
SELECT DISTINCT NICK FROM MEMBER;

-- INSERT
INSERT INTO MEMBER(ID, PWD, NICK , LOCATION) VALUES('USER01', '1234', 'NICK01' , '서울');
INSERT INTO MEMBER(ID, PWD, NICK , AGE) VALUES('USER02', '2222', 'NICK02' , 20);
INSERT INTO MEMBER(ID, PWD, NICK , AGE) VALUES('USER03', '3333', 'NICK03' , 30);
INSERT INTO MEMBER(ID, PWD, NICK , AGE) VALUES('USER04', '3333', 'NICK03' , 40);
INSERT INTO MEMBER(ID, PWD, NICK , LOCATION) VALUES('USER05', '1234', 'NICK05' , '제주도');



-- UPDATE
UPDATE MEMBER 
    SET PWD = '1111'
    WHERE ID = 'USER01';
    
-- DELETE
DELETE MEMBER
    WHERE ID = 'USER02';



-- 문자열 더하기
SELECT CONCAT(CONCAT('안녕' , '하세요') , 'ZZZ') 칼럼명01 FROM DUAL;

-- ID가 USER01인 회원 조회
SELECT * FROM MEMBER WHERE ID = 'USER01';

-- LOCATION이 서울 인 회원 조회
SELECT * FROM MEMBER WHERE LOCATION = '서울';

-- LOCATION이 NULL 인 회원 조회
SELECT * FROM MEMBER WHERE LOCATION IS NULL;

-- 나이가 10 이상 25 이하
SELECT * FROM MEMBER WHERE AGE >= 10 AND AGE <= 25;
SELECT * FROM MEMBER WHERE AGE BETWEEN 10 AND 25;

-- 거주지가 울 이라는 글자로 끝나는 회원의 닉네임을 조회
SELECT NICK , LOCATION FROM MEMBER WHERE LOCATION LIKE '%울';

-- 거주지에 주 라는 글자가 들어가는 회원의 모든칼럼 조회
SELECT * FROM MEMBER WHERE LOCATION LIKE '%';

-- 나이가 20살 이거나 30살 이거나 40살 회원 의 모든 칼럼 조회
SELECT * FROM MEMBER WHERE AGE = 20 OR AGE = 30 OR AGE = 40; 
SELECT * FROM MEMBER WHERE AGE IN (20,30,40);

-- 멤버 테이블 조회 , 모든칼럼 , 나이순서대로
SELECT * FROM MEMBER ORDER BY AGE DESC NULLS FIRST;







